# Generated by Django 5.1.1 on 2024-09-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_name_image_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True, verbose_name='Логін')),
                ('name', models.CharField(max_length=255, verbose_name='Імʼя')),
                ('pwd', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
        ),
    ]
